name: Bump version and push tag

on:
  push:
    branches:
      - main # 或你使用的默认分支名称，比如master

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Bump version
        run: |
          git config --global user.email "six.django@gmail.com"
          git config --global user.name "Django"
          npm version patch -m "chore(release): bump version to %s"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.G_TOKEN }}
          branch: main # 或你使用的默认分支名称，比如 master
